# hyprarch: mismo margen para las aplicaciones que usan la capa de PulseAudio (reproductores, navegador, pw-play)
pulse.properties = {
    pulse.min.req     = 1024/48000
    pulse.default.req = 1024/48000
    pulse.min.quantum = 1024/48000
}
stream.properties = {
    node.latency = 1024/48000
}
