# hyprarch: PipeWire/WirePlumber no suspende las salidas de audio por inactividad (evita chasquidos al despertar)
monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.*" }
      { node.name = "~alsa_input.*" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]