# hyprarch: evita el «pop» al despertar la tarjeta de sonido (no se suspende) y da margen extra al buffer de ALSA
monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.*" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        api.alsa.headroom               = 1024
        api.alsa.period-size            = 1024
      }
    }
  }
]
